package org.miaomiao.assembly.model;

import org.miaomiao.assembly.LoadException;
import org.miaomiao.loader.InputStreamReader;

import java.io.IOException;

/**
 * The .text section of a PE file is a read-only section. In a managed PE file, it contains metadata tables, IL code, the Import tables, the common language runtime header, and an unmanaged start-up stub for the CLR. In the image files generated by the IL assembler, this section also contains managed resources, the strong name signature hash, the debug data, and unman- aged export stubs.
 */
public class TextSectionData extends SectionData {

    @Override
    public void parse(InputStreamReader reader) throws IOException, LoadException {
        super.jumpToStart(reader);
    }

}
